default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: lemons_development
test:
  <<: *default
  database: lemons_test
production:
  <<: *default
  database: lemons_production
  username: lemons
  password: <%= ENV['LEMONS_DATABASE_PASSWORD'] %>
